#!/data/data/com.termux/files/usr/bin/bash

# Builds ~/.local/bin/claude-exec-shim, the argv[0]-preserving launcher that the
# Android block of dot_zshenv.tmpl points $CLAUDE_CODE_EXECPATH at.
#
# Why it exists:
#   Claude Code's Bash tool appends its own `grep` and `find` zsh functions to the
#   shell snapshot it sources into every tool call. Both run the Claude Code binary
#   itself under a different argv[0] -- `ARGV0=ugrep "$CLAUDE_CODE_EXECPATH" ...`
#   and `ARGV0=bfs ...` -- because that binary is multi-call and dispatches on
#   argv[0] alone. $CLAUDE_CODE_EXECPATH points straight at the musl build, and by
#   then ~/.zshenv has restored LD_PRELOAD for termux-exec, so the musl loader is
#   handed a bionic library it cannot relocate and exits 127 before main() with
#   eleven "symbol not found" lines. Every grep and find in a tool call fails.
#
#   The `claude` wrapper already solves this for the CLI itself (it parks
#   LD_PRELOAD in TERMUX_ETC_LD_PRELOAD before the exec), but it cannot be reused
#   here: it is a "#!" script, and the kernel replaces argv[0] with the interpreter
#   path when it runs one, so "ugrep" is lost and the binary would start as the
#   Claude CLI with ugrep's flags. Only a real executable passes argv through
#   untouched -- which is the whole reason this shim is C and not a wrapper script
#   like every other tool in ~/.local/bin.
#
# Why a run_after_ script:
#   `clang` is installed by run_once_before_android-002, so the build cannot happen
#   in a run_once_before_ wrapper script. Running after every apply also lets the
#   shim come back if the binary is deleted; the work is skipped when it is already
#   newer than its source, so a normal apply costs two stat() calls.

set -euo pipefail

SHIM_SOURCE_DIR="$HOME/.local/share/claude-exec-shim"
SHIM_SOURCE="$SHIM_SOURCE_DIR/claude-exec-shim.c"
SHIM_BINARY="$HOME/.local/bin/claude-exec-shim"

mkdir -p "$SHIM_SOURCE_DIR" "$HOME/.local/bin"

cat > "$SHIM_SOURCE.tmp" << 'SHIM_EOF'
/*
 * claude-exec-shim -- exec Claude Code's musl binary without Termux's bionic
 * LD_PRELOAD shims, preserving argv[0].
 *
 * Generated by .chezmoiscripts/run_after_android-006-build-claude-exec-shim.sh in
 * rios0rios0/dotfiles. Do not edit directly -- the next `chezmoi apply` overwrites
 * it and rebuilds the binary.
 *
 * Reads the real program from TERMUX_CLAUDE_EXEC_TARGET (set by ~/.zshenv from the
 * $CLAUDE_CODE_EXECPATH that Claude Code exports) and execs it with argv untouched,
 * so the multi-call binary still sees the "ugrep" or "bfs" argv[0] that Claude
 * Code's grep/find wrapper functions gave it.
 *
 * LD_PRELOAD is parked in TERMUX_ETC_LD_PRELOAD rather than dropped -- the same
 * contract the `claude` wrapper and termux-etc-mount implement -- so any bionic
 * shell started underneath gets termux-exec's shebang rewriting back from
 * ~/.zshenv instead of inheriting an unset variable.
 */

#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

int main(int argc, char *argv[]) {
    (void)argc;

    const char *target = getenv("TERMUX_CLAUDE_EXEC_TARGET");
    if (target == NULL || *target == '\0') {
        fprintf(stderr,
                "[claude-exec-shim] ERROR: TERMUX_CLAUDE_EXEC_TARGET is unset; "
                "~/.zshenv sets it from $CLAUDE_CODE_EXECPATH\n");
        return 127;
    }

    /*
     * Refuse to exec ourselves. Nothing should point the target back here, but a
     * stale environment that did would otherwise fork-bomb the phantom process
     * budget rather than fail.
     */
    char self_path[PATH_MAX];
    char target_path[PATH_MAX];
    if (realpath("/proc/self/exe", self_path) != NULL &&
        realpath(target, target_path) != NULL &&
        strcmp(self_path, target_path) == 0) {
        fprintf(stderr,
                "[claude-exec-shim] ERROR: TERMUX_CLAUDE_EXEC_TARGET points at this "
                "shim; refusing to exec itself\n");
        return 127;
    }

    const char *preload = getenv("LD_PRELOAD");
    if (preload != NULL && *preload != '\0') {
        if (setenv("TERMUX_ETC_LD_PRELOAD", preload, 1) != 0) {
            fprintf(stderr,
                    "[claude-exec-shim] ERROR: cannot park LD_PRELOAD: %s\n",
                    strerror(errno));
            return 127;
        }
    }
    if (unsetenv("LD_PRELOAD") != 0) {
        fprintf(stderr,
                "[claude-exec-shim] ERROR: cannot unset LD_PRELOAD: %s\n",
                strerror(errno));
        return 127;
    }

    execv(target, argv);

    fprintf(stderr, "[claude-exec-shim] ERROR: cannot execute '%s': %s\n", target,
            strerror(errno));
    return 127;
}
SHIM_EOF

if [ ! -f "$SHIM_SOURCE" ] || ! cmp -s "$SHIM_SOURCE.tmp" "$SHIM_SOURCE"; then
    mv -f "$SHIM_SOURCE.tmp" "$SHIM_SOURCE"
else
    rm -f "$SHIM_SOURCE.tmp"
fi

# Nothing to do when the binary is already built from this exact source.
if [ -x "$SHIM_BINARY" ] && [ "$SHIM_BINARY" -nt "$SHIM_SOURCE" ]; then
    exit 0
fi

compiler=""
for candidate in clang cc gcc; do
    if command -v "$candidate" > /dev/null 2>&1; then
        compiler="$candidate"
        break
    fi
done

# The Android installer lists `clang` among its requirements, so this only happens
# on a machine whose apply has not reached it yet. Leaving the shim unbuilt is safe:
# ~/.zshenv skips the repoint when the binary is missing, which is the behaviour
# from before this shim existed.
if [ -z "$compiler" ]; then
    echo "[claude-exec-shim] WARN: no C compiler found; skipping build" >&2
    echo "[claude-exec-shim]       install one with 'pkg install clang' and re-run 'chezmoi apply'" >&2
    exit 0
fi

echo "[claude-exec-shim] building claude-exec-shim with $compiler..." >&2

if ! "$compiler" -O2 -Wall -Wextra -o "$SHIM_BINARY.tmp" "$SHIM_SOURCE"; then
    rm -f "$SHIM_BINARY.tmp"
    echo "[claude-exec-shim] ERROR: build failed; grep and find inside Claude Code" >&2
    echo "[claude-exec-shim]        tool calls will keep failing with exit 127" >&2
    exit 1
fi

mv -f "$SHIM_BINARY.tmp" "$SHIM_BINARY"
chmod +x "$SHIM_BINARY"

echo "[claude-exec-shim] claude-exec-shim built successfully" >&2
