#!/data/data/com.termux/files/usr/bin/bash

# Creates the 'codex' wrapper for the Codex CLI's aarch64-unknown-linux-musl build.
#
# Why not npm:
#   `npm install -g @openai/codex` cannot work on Termux. The package is a Node
#   launcher plus one optional dependency per platform, and the platform package
#   (`@openai/codex-linux-arm64`) declares `os: linux` in its package.json while
#   Termux's Node reports `android`, so npm skips it silently and the launcher
#   throws "Missing optional dependency @openai/codex-linux-arm64". GitHub
#   publishes the same binary as a statically linked musl executable, which this
#   wrapper downloads and runs directly -- one process fewer than the npm launcher
#   (node -> codex), which matters under Android's phantom-process budget.
#
# Why a wrapper at all (every point verified on a device):
#   - DNS: musl reads /etc/resolv.conf through direct syscalls and Android has no
#     such file, so the binary runs through termux-etc-mount (Tier 3 of
#     rios0rios0/termux-etc-redirect), like the claude wrapper. Tier 2
#     (termux-etc-seccomp) is wrong here: its blanket SIGSYS -> ENOSYS rewrite
#     reaches every descendant, and codex spawns Node for tool calls (npm, test
#     runners), where it surfaces as `ENOSYS: lstat`.
#   - TLS: codex (rustls) probes the usual CA bundle paths with stat(), which
#     Tier 3 does not redirect (openat only), so it starts with an empty root
#     store and every handshake fails with "invalid peer certificate:
#     UnknownIssuer". SSL_CERT_FILE names Termux's bundle directly.
#   - Sandbox: codex's Linux sandbox is bubblewrap, which needs unprivileged user
#     namespaces; Android's SELinux policy denies them (`unshare(CLONE_NEWUSER)`
#     returns EINVAL, and bwrap cannot even read /proc/sys/kernel/overflowuid),
#     so `read-only` and `workspace-write` both panic before running a command.
#     The wrapper defaults `sandbox_mode` to `danger-full-access` -- the only
#     mode that works -- unless CODEX_WRAPPER_KEEP_SANDBOX=1. Approval prompts
#     are unaffected. Claude Code has no sandbox on Termux either.
#   - Updates: `codex update` refuses a manual install ("Could not detect the
#     Codex installation method"), so the wrapper handles them. Being static, the
#     binary needs no musl loader and no patchelf step, unlike Claude Code.
#
# Update model (same as the claude wrapper):
#   - check at most once per 24h (timestamp at $XDG_CACHE_HOME/codex-wrapper/)
#   - the check runs in the background; codex startup never blocks on it
#   - new versions land at ~/.local/share/codex/versions/<X.Y.Z>/codex and are
#     used on the next launch -- the running session keeps its current build
#   - the most recent KEEP_VERSIONS=3 builds are retained; older are pruned
#   - with nothing installed, the first launch downloads the latest release in
#     the foreground; that is how the Android dependency installer bootstraps it
#
# Override knobs (read by the emitted wrapper):
#   CODEX_WRAPPER_NO_AUTO_UPDATE  set to "1" to skip the background update check
#                                 (this also hands the startup update nag back to codex)
#   CODEX_WRAPPER_FORCE_VERSION   pin to a specific installed X.Y.Z
#   CODEX_WRAPPER_KEEP_SANDBOX    set to "1" to leave sandbox_mode alone

set -e

echo "[codex-wrapper] creating codex in ~/.local/bin..." >&2

mkdir -p "$HOME/.local/bin"

cat > "$HOME/.local/bin/codex" << 'CODEX_EOF'
#!/data/data/com.termux/files/usr/bin/bash
# Wraps the Codex CLI (aarch64-unknown-linux-musl, static) through
# termux-etc-mount with a non-blocking, rate-limited auto-update check.
# `codex update` cannot update a manual install, so this wrapper does.
#
# Generated by .chezmoiscripts/run_once_before_android-001f-create-codex-wrapper.sh
# in rios0rios0/dotfiles; that script's header explains every knob below.

set -u

# Identity + HOME for libc fallbacks (Android /etc/passwd is sparse).
export USER="${USER:-$(id -un)}"
export HOME="${HOME:-/data/data/com.termux/files/home}"

# Park Termux's bionic LD_PRELOAD shims in TERMUX_ETC_LD_PRELOAD instead of
# dropping them. The static codex binary ignores LD_PRELOAD either way, but
# termux-etc-mount removes it before the exec, and the bionic shells behind
# codex's tool calls need it back or every `#!/usr/bin/env` script they run
# fails with exit 127 -- ~/.zshenv restores it from the parked copy. Parking
# here as well keeps a wrapper and a redirector of different vintages agreeing.
if [ -n "${LD_PRELOAD:-}" ]; then
    export TERMUX_ETC_LD_PRELOAD="$LD_PRELOAD"
fi
unset LD_PRELOAD

# Default PREFIX so `set -u` doesn't trip when launched from a non-Termux
# environment that didn't export it.
: "${PREFIX:=/data/data/com.termux/files/usr}"
export PREFIX

# rustls finds no CA roots on Android (see the generating script), so name
# Termux's bundle explicitly. A value already in the environment wins.
: "${SSL_CERT_FILE:=$PREFIX/etc/tls/cert.pem}"
export SSL_CERT_FILE

VERSIONS_DIR="$HOME/.local/share/codex/versions"
RELEASES_URL="https://github.com/openai/codex/releases"
ASSET="codex-aarch64-unknown-linux-musl"
STAMP_FILE="${XDG_CACHE_HOME:-$HOME/.cache}/codex-wrapper/last-update-check"
LOGFILE="${XDG_CACHE_HOME:-$HOME/.cache}/codex-wrapper/update.log"
CHECK_INTERVAL_SECONDS=$((24 * 3600))
KEEP_VERSIONS=3
SEMVER_REGEX='^[0-9]+\.[0-9]+\.[0-9]+$'

# HTTPS-only download, as the installer scripts do it: a redirect to plain
# HTTP is refused instead of followed.
download_https_only() {
    curl -fsSL --proto '=https' --proto-redir '=https' "$@"
}

# Print every installed version -- a directory under $VERSIONS_DIR named X.Y.Z
# that holds an executable `codex` -- in ascending semver order. Anything else
# under the directory (an interrupted download, a stray file) is ignored.
list_installed_versions() {
    local entry name
    local versions=()
    for entry in "$VERSIONS_DIR"/*/codex; do
        [ -f "$entry" ] && [ -x "$entry" ] || continue
        name=${entry%/codex}
        name=${name##*/}
        [[ "$name" =~ $SEMVER_REGEX ]] || continue
        versions+=("$name")
    done
    [ "${#versions[@]}" -eq 0 ] && return 0
    printf '%s\n' "${versions[@]}" | sort -V
}

# Resolve the newest release. GitHub answers /releases/latest with a redirect
# to the tag page, so one HEAD request that follows it suffices without the
# rate-limited API. Stable releases only: a pre-release never becomes "latest".
resolve_latest_version() {
    local location
    location=$(download_https_only --max-time 10 -I -o /dev/null -w '%{url_effective}' "$RELEASES_URL/latest") || return 1
    location=${location##*/rust-v}
    [[ "$location" =~ $SEMVER_REGEX ]] || return 1
    printf '%s\n' "$location"
}

# Download release X.Y.Z to $VERSIONS_DIR/X.Y.Z/codex. The archive is unpacked
# in a temporary directory on the same filesystem and moved into place only
# after the binary has proven it runs, so list_installed_versions never sees a
# half-written version. Stderr is intentionally not suppressed: the callers
# either show it to the user (bootstrap) or send it to $LOGFILE (updater).
install_version() {
    local version="$1"
    local tmp

    mkdir -p "$VERSIONS_DIR" || return 1
    tmp=$(mktemp -d "$VERSIONS_DIR/.install-XXXXXX") || return 1

    if ! download_https_only --max-time 600 -o "$tmp/$ASSET.tar.gz" \
            "$RELEASES_URL/download/rust-v$version/$ASSET.tar.gz" \
        || ! tar -xzf "$tmp/$ASSET.tar.gz" -C "$tmp" "$ASSET" \
        || ! mv "$tmp/$ASSET" "$tmp/codex" \
        || ! chmod +x "$tmp/codex" \
        || ! "$tmp/codex" --version >/dev/null; then
        rm -rf "$tmp"
        return 1
    fi
    rm -f "$tmp/$ASSET.tar.gz"

    # A concurrent launch may have installed the same version meanwhile; a
    # leftover directory without a working binary is replaced.
    if [ -x "$VERSIONS_DIR/$version/codex" ]; then
        rm -rf "$tmp"
        return 0
    fi
    rm -rf "${VERSIONS_DIR:?}/$version"
    mv "$tmp" "$VERSIONS_DIR/$version" || { rm -rf "$tmp"; return 1; }
}

# Keep the newest $KEEP_VERSIONS builds; non-semver entries are never touched.
prune_old_versions() {
    local total
    total=$(list_installed_versions | wc -l)
    if [ "$total" -gt "$KEEP_VERSIONS" ]; then
        list_installed_versions \
            | head -n "$((total - KEEP_VERSIONS))" \
            | while IFS= read -r old; do rm -rf "${VERSIONS_DIR:?}/$old"; done
    fi
}

run_update_check() {
    [ "${CODEX_WRAPPER_NO_AUTO_UPDATE:-0}" = "1" ] && return 0

    mkdir -p "$(dirname "$STAMP_FILE")" || return 0

    if [ -f "$STAMP_FILE" ]; then
        local last_check now
        last_check=$(stat -c '%Y' "$STAMP_FILE" 2>/dev/null || echo 0)
        now=$(date +%s)
        [ $((now - last_check)) -lt "$CHECK_INTERVAL_SECONDS" ] && return 0
    fi

    local latest
    latest=$(resolve_latest_version) || return 0

    # Already on the latest published build -- record the successful check
    # and return without touching disk.
    if [ -x "$VERSIONS_DIR/$latest/codex" ]; then
        touch "$STAMP_FILE"
        return 0
    fi

    install_version "$latest" || return 0
    # The stamp is written only after the install succeeds so that a failed
    # download retries on the next launch instead of silently waiting out the
    # 24h interval with no new binary on disk.
    touch "$STAMP_FILE"
    echo "[codex-wrapper] auto-updated to $latest (used on next launch)" >&2
    prune_old_versions
}

mkdir -p "$VERSIONS_DIR" "$(dirname "$LOGFILE")" 2>/dev/null || true

if [ -z "$(list_installed_versions)" ]; then
    # Nothing installed yet: fetch the latest release in the foreground. This
    # is the path the Android dependency installer takes on a fresh machine.
    echo "[codex-wrapper] no Codex CLI version installed in $VERSIONS_DIR" >&2
    if ! latest=$(resolve_latest_version); then
        echo "[codex-wrapper] ERROR: could not resolve the latest release from $RELEASES_URL/latest" >&2
        exit 1
    fi
    echo "[codex-wrapper] downloading Codex CLI $latest ($ASSET, about 90 MB)..." >&2
    if ! install_version "$latest"; then
        echo "[codex-wrapper] ERROR: failed to install Codex CLI $latest" >&2
        exit 1
    fi
    mkdir -p "$(dirname "$STAMP_FILE")" 2>/dev/null && touch "$STAMP_FILE"
    echo "[codex-wrapper] installed Codex CLI $latest" >&2
else
    # Fire-and-forget background update check. Output goes to a logfile so the
    # terminal stays clean, and any failure is silent -- codex startup never
    # blocks or fails because of an update issue.
    ( run_update_check ) >> "$LOGFILE" 2>&1 &
    disown 2>/dev/null || true
fi

# Pin or pick the newest installed version. CODEX_WRAPPER_FORCE_VERSION must
# name an installed version; otherwise the newest one is used, with a warning.
if [ -n "${CODEX_WRAPPER_FORCE_VERSION:-}" ]; then
    if [ -x "$VERSIONS_DIR/$CODEX_WRAPPER_FORCE_VERSION/codex" ]; then
        CODEX_VERSION="$CODEX_WRAPPER_FORCE_VERSION"
    else
        echo "[codex-wrapper] WARN: CODEX_WRAPPER_FORCE_VERSION=$CODEX_WRAPPER_FORCE_VERSION is not installed; using the newest version" >&2
        CODEX_VERSION=$(list_installed_versions | tail -1)
    fi
else
    CODEX_VERSION=$(list_installed_versions | tail -1)
fi
CODEX_BIN="$VERSIONS_DIR/$CODEX_VERSION/codex"

if ! command -v termux-etc-mount >/dev/null 2>&1; then
    echo "[codex-wrapper] ERROR: termux-etc-mount not found in PATH" >&2
    echo "[codex-wrapper]        install rios0rios0/termux-etc-redirect (provides" >&2
    echo "[codex-wrapper]        termux-etc-mount used to redirect /etc/* to \$PREFIX/etc/*)" >&2
    exit 1
fi

# Take Termux's wake lock before handing off to codex. Once the screen is off
# Android pauses the CPU of a backgrounded app, which mid-task looks like a
# hang and, past a grace period, a kill. The lock is NOT scoped to this
# session: the `exec` below leaves no process to release it, so it persists
# until `termux-wake-unlock` is run by hand. It is idempotent, and it comes
# from termux-tools, so its absence is not an error.
if command -v termux-wake-lock >/dev/null 2>&1; then
    termux-wake-lock 2>/dev/null || true
fi

# The sandbox cannot work on Termux (see the generating script), so default
# sandbox_mode to the only mode that runs. `-c` is a global option that every
# subcommand accepts, and a later `-c sandbox_mode=...` or `--sandbox` on the
# command line still wins. Codex's own startup update check is silenced only
# while this wrapper's updater is active: codex reports "install method:
# other" and would only ever suggest a manual download.
OVERRIDES=()
if [ "${CODEX_WRAPPER_KEEP_SANDBOX:-0}" != "1" ]; then
    OVERRIDES+=(-c 'sandbox_mode="danger-full-access"')
fi
if [ "${CODEX_WRAPPER_NO_AUTO_UPDATE:-0}" != "1" ]; then
    OVERRIDES+=(-c 'check_for_update_on_startup=false')
fi

exec termux-etc-mount "$CODEX_BIN" ${OVERRIDES[@]+"${OVERRIDES[@]}"} "$@"
CODEX_EOF

chmod +x "$HOME/.local/bin/codex"

echo "[codex-wrapper] codex wrapper created successfully" >&2
